stages:
  - test
  - report

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=C:\\m2\\repository"
  SHELL: ["pwsh", "-Command"]

cache:
  paths:
    - C:/m2/repository/
    - target/

# Запуск тестов
run_tests:
  stage: test
  tags:
    - docker
  image: mcr.microsoft.com/windowsservercore:ltsc2022
  before_script:
    - choco install maven -y --no-progress
  script:
    - mvn $MAVEN_CLI_OPTS clean test
  artifacts:
    when: always
    paths:
      - target/allure-results/
    reports:
      junit: target/surefire-reports/**/*.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"

# Генерация отчета Allure
generate_report:
  stage: report
  tags:
    - docker
  image: mcr.microsoft.com/windowsservercore:ltsc2022
  before_script:
    - choco install maven -y --no-progress
  script:
    - mvn allure:report
  artifacts:
    paths:
      - target/allure-report/
    expire_in: 1 week
  needs: ["run_tests"]
  only:
    - main